<a href="https://colab.research.google.com/github/Phil-Schwarz/TQA/blob/phil_test_range/Elasticsearch_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!nvidia-smi

Sat May 15 12:18:48 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   34C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
!pip install farm-haystack

     |████████████████████████████████| 153kB 31.5MB/s 
     |████████████████████████████████| 204kB 32.6MB/s 
     |████████████████████████████████| 51kB 7.8MB/s 
     |████████████████████████████████| 51kB 7.7MB/s 
     |████████████████████████████████| 81kB 11.4MB/s 
     |████████████████████████████████| 327kB 49.7MB/s 
     |████████████████████████████████| 327kB 48.5MB/s 
     |████████████████████████████████| 92kB 10.4MB/s 
     |████████████████████████████████| 983kB 48.2MB/s 
     |████████████████████████████████| 5.5MB 35.2MB/s 
     |████████████████████████████████| 102kB 11.0MB/s 
     |████████████████████████████████| 8.2MB 19.8MB/s 
     |████████████████████████████████| 348kB 49.6MB/s 
     |████████████████████████████████| 61kB 8.4MB/s 
     |████████████████████████████████| 3.0MB 48.9MB/s 
     |████████████████████████████████| 3.8MB 49.3MB/s 
     |████████████████████████████████| 327kB 46.4MB/s 
     |████████████████████████████████| 1.5MB 17.0MB/s 


In [ ]:
!pip install lineflow
!pip install transformers
!pip install pytorch-lightning
!pip install json_lines

# Albert requires SentencePiece
!pip install SentencePiece

  Created wheel for lineflow: filename=lineflow-0.6.4-cp37-none-any.whl size=23201 sha256=f5528990f966fab8a779eea9e172123a8040d7e5e928f9545ebb567f06f64cb5
  Stored in directory: /root/.cache/pip/wheels/b9/11/32/a6120f98d7d11ed8cf1b28b265a12a4b72842da341c13384c1
  Created wheel for arrayfiles: filename=arrayfiles-0.0.1-cp37-none-any.whl size=5434 sha256=6c210b4f6916661e43425428e1f82b138b6e1ba24d4cd68077188a86e70cf29c
  Stored in directory: /root/.cache/pip/wheels/2c/43/9b/fb9049f9c3931d703182bd45418c3e8d67a6b6eded6325e16e
Successfully built lineflow arrayfiles
     |████████████████████████████████| 2.3MB 26.6MB/s 
     |████████████████████████████████| 3.3MB 47.6MB/s 
     |████████████████████████████████| 901kB 40.0MB/s 
     |████████████████████████████████| 808kB 27.6MB/s 
     |████████████████████████████████| 276kB 46.0MB/s 
     |████████████████████████████████| 829kB 51.2MB/s 
     |████████████████████████████████| 645kB 48.8MB/s 
     |████████████████████████████████| 11

In [ ]:
import sys
print (sys.path)

['', '/content', '/env/python', '/usr/lib/python37.zip', '/usr/lib/python3.7', '/usr/lib/python3.7/lib-dynload', '/usr/local/lib/python3.7/dist-packages', '/usr/lib/python3/dist-packages', '/usr/local/lib/python3.7/dist-packages/IPython/extensions', '/root/.ipython']


In [ ]:
!pip install elasticsearch

In [ ]:
#-------------------Test Area ---------------------------

In [ ]:
# -----SHOULD USE THE GOOGLE DRIVE ---------------
# This is downloading elasticsearch and unzipping it, then giving you access rights to it, but it is a clean version, not the correct one
#! wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.9.2-linux-x86_64.tar.gz -q
#! tar -xzf elasticsearch-7.9.2-linux-x86_64.tar.gz
#! chown -R daemon:daemon elasticsearch-7.9.2

In [ ]:
from google.colab import drive

drive.mount("/content/gdrive")

Mounted at /content/gdrive


In [ ]:
#!chmod 755 /content/gdrive/MyDrive/Fachpraktikum/elasticsearch-7.12.1/bin/elasticsearch

In [ ]:
#! chown -R daemon:daemon /content/gdrive/MyDrive/Fachpraktikum/elasticsearch-7.12.1

In [ ]:
#!/content/gdrive/MyDrive/Fachpraktikum/elasticsearch-7.12.1/bin/elasticsearch

In [ ]:
# tried this after moving the folder to the "home" directory
! chown -R daemon:daemon elasticsearch-7.12.1

In [ ]:
import os
from subprocess import Popen, PIPE, STDOUT
es_server = Popen(['elasticsearch-7.12.1/bin/elasticsearch'], #--------- change directory here
                   stdout=PIPE, stderr=STDOUT,
                   preexec_fn=lambda: os.setuid(1)  # start elasticsearch as daemon
                  )
# wait until ES has started
! sleep 30

In [ ]:
#import os
#from subprocess import Popen, PIPE, STDOUT
#es_server = Popen(['elasticsearch-7.9.2/bin/elasticsearch'],
#                   stdout=PIPE, stderr=STDOUT,
#                   preexec_fn=lambda: os.setuid(1)  # as daemon
                  )
# wait until ES has started
#! sleep 30

In [ ]:
#---------------- Test Area end ------------------------

In [ ]:
import haystack

import pandas as pd
import matplotlib.pyplot as plt
import io
import unicodedata
import numpy as np
import re
import string

import csv
                 
import pickle

import json

from six import string_types

import tqdm

from haystack.preprocessor.cleaning import clean_wiki_text
from haystack.preprocessor.utils import convert_files_to_dicts, fetch_archive_from_http
from haystack.reader.farm import FARMReader
from haystack.reader.transformers import TransformersReader
from haystack.utils import print_answers

import elasticsearch

05/15/2021 12:16:46 - INFO - faiss.loader -   Loading faiss with AVX2 support.
05/15/2021 12:16:46 - INFO - faiss.loader -   Loading faiss.
05/15/2021 12:16:47 - INFO - farm.modeling.prediction_head -   Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .


In [ ]:
!curl localhost:9200  # see if elasticsearch server is up

{
  "name" : "021a416c7d08",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "ZOeSZHnBS4mXl2VQFDCtaw",
  "version" : {
    "number" : "7.9.2",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "d34da0ea4a966c4e49417f2da2f244e3e97b4e6e",
    "build_date" : "2020-09-23T00:45:33.626720Z",
    "build_snapshot" : false,
    "lucene_version" : "8.6.2",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}


In [ ]:
from haystack.document_store.elasticsearch import ElasticsearchDocumentStore
document_store = ElasticsearchDocumentStore(host="localhost", username="", password="", index="document")

05/15/2021 12:16:51 - INFO - elasticsearch -   HEAD http://localhost:9200/ [status:200 request:0.012s]
05/15/2021 12:16:51 - INFO - elasticsearch -   HEAD http://localhost:9200/document [status:200 request:0.013s]
05/15/2021 12:16:51 - INFO - elasticsearch -   GET http://localhost:9200/document [status:200 request:0.005s]
05/15/2021 12:16:51 - INFO - elasticsearch -   PUT http://localhost:9200/document/_mapping [status:200 request:0.019s]
05/15/2021 12:16:51 - INFO - elasticsearch -   HEAD http://localhost:9200/label [status:200 request:0.003s]


In [ ]:
document_store.get_document_count()   # see if indexes are there

05/15/2021 12:17:21 - INFO - elasticsearch -   POST http://localhost:9200/document/_count [status:200 request:0.014s]


0

In [ ]:
#----------------- only continue if this returns a large number (aka. you are using the correct elasticsearch server)

In [ ]:
from haystack.retriever.sparse import ElasticsearchRetriever
retriever = ElasticsearchRetriever(document_store=document_store)

In [ ]:
print(retriever.retrieve(query="What colour is the sun? Yellow", top_k=10))

05/14/2021 18:21:24 - INFO - elasticsearch -   POST http://localhost:9200/document/_search [status:200 request:3.063s]


[{'text': 'The Sun has a surface temperature of 5,500 degrees Celcius, its colour appears yellow.\n', 'id': '7b14167f-a62f-4721-a818-3be28fe1e15d', 'score': 20.915186, 'probability': 0.9317824975732657, 'question': None, 'meta': {}, 'embedding': None}, {'text': 'For example, when the sun is higher in the sky, pillars are white or bright yellow in colour.\n', 'id': '4232d0de-617e-4118-bbb4-bed4f6a7658f', 'score': 20.879787, 'probability': 0.931500697429873, 'question': None, 'meta': {}, 'embedding': None}, {'text': 'Why is the Sun yellow ?\n', 'id': '8b75a496-4496-4453-b315-770cd56e0b6d', 'score': 20.163853, 'probability': 0.9255652428163195, 'question': None, 'meta': {}, 'embedding': None}, {'text': 'The oil is transparent pale yellow or yellow-grey in colour.\n', 'id': '17e764ca-7fa3-41d7-bb15-5fb5ad5efc46', 'score': 20.113697, 'probability': 0.9251321563870804, 'question': None, 'meta': {}, 'embedding': None}, {'text': 'The sun is a yellow dwarf.\n', 'id': '6e8739ee-611d-4470-ad24-e2

In [ ]:
for result in retriever.retrieve(query="What colour is the sun? Yellow", top_k=3):
    print(result.text)
    #    _article = _article + result["text"] + ". "

05/14/2021 13:34:41 - INFO - elasticsearch -   POST http://localhost:9200/document/_search [status:200 request:0.027s]


The Sun has a surface temperature of 5,500 degrees Celcius, its colour appears yellow.

For example, when the sun is higher in the sky, pillars are white or bright yellow in colour.

Why is the Sun yellow ?



In [ ]:
from typing import Dict
from pathlib import Path
from functools import partial
from collections import OrderedDict
from argparse import ArgumentParser

import lineflow as lf
from transformers import AlbertForMultipleChoice, AlbertTokenizer, AdamW
import pytorch_lightning as pl

import torch
from torch.utils.data import DataLoader, SequentialSampler, RandomSampler
import json_lines
import pickle
from pytorch_lightning.metrics import functional as FM

In [ ]:
MAX_LEN = 256
NUM_LABELS = 4
label_map = {"A": 0, "B": 1, "C": 2, "D": 3}
BATCH_SIZE = 8

In [ ]:
def load_dataloader_from_cache(tokenizer,cachedir: str = "./"):
    cachedir = Path(cachedir)
    test_file_name = "test_openbook.cache"
    test_path = Path(cachedir / test_file_name)
    if test_path.exists():
        print(f'Loading data from {test_file_name}...')
        with test_path.open('rb') as f:
            test_cache = pickle.load(f)

    test_dataloader = DataLoader(
            lf.core.CacheDataset(test_cache),
            batch_size=BATCH_SIZE
            )

    return test_dataloader

In [ ]:
t_dataset = []

In [ ]:
def raw_samples_to_dataset(samples, daset):
    datas = []
    i = 0
    for sample in samples:
        i+=1
        if i%250 == 0:
            print(i)
        _id = sample["id"]
        _facts = []
        _uniques = []
        _rscore = []
        _article = ""
        for idx in range(len(sample['question']['choices'])): 
            for result in retriever.retrieve(query=sample["question"]['stem'] + " " + sample["question"]['choices'][idx]['text'], top_k=4):
#               print(sample["question"]['stem'] + " " + sample["question"]['choices'][idx]['text'])
                _facts.append(result.text)
                _rscore.append(result.score)
#        print(_article)
        for fact in _facts:
#            print(fact)
#            print(_article)
            if fact not in _uniques:
                _uniques.append(fact)
                _article = _article + ". " + fact
#                print(_article)
                
#        print("---------------------------------")
#        print(_article)
        _question = sample["question"]['stem']
        _options = []
        _answer = sample["answerKey"]
        for idx in range(len(sample['question']['choices'])): 
            _options.append(sample["question"]['choices'][idx]['text'])

        data = {
                "id": _id,
                "facts": _facts,
                "article": _article,
                "options": _options,
                "question": _question,
                "answer": _answer,
                "optionscore": [],
                "rscore": _rscore
                }
        datas.append(data)
        daset.append(data)
    return lf.Dataset(datas)


def preprocess(tokenizer: AlbertTokenizer, x: Dict) -> Dict:

    choices_features = []

    option: str
    for option in x["options"]:
        text_a = x["article"]
        text_b = x["question"] + " " + option

        inputs = tokenizer.encode_plus(
                text_a,
                text_b,
                add_special_tokens=True,
                max_length=MAX_LEN
                )
        input_ids, token_type_ids = inputs["input_ids"], inputs["token_type_ids"]
        attention_mask = [1] * len(input_ids)

        pad_token_id = tokenizer.pad_token_id
        padding_length = MAX_LEN - len(input_ids)
        input_ids = input_ids + ([pad_token_id] * padding_length)
        attention_mask = attention_mask + ([0] * padding_length)
        token_type_ids = token_type_ids + ([pad_token_id] * padding_length)

        assert len(input_ids) == MAX_LEN, "Error with input length {} vs {}".format(len(input_ids), MAX_LEN)
        assert len(attention_mask) == MAX_LEN, "Error with input length {} vs {}".format(len(attention_mask), MAX_LEN)
        assert len(token_type_ids) == MAX_LEN, "Error with input length {} vs {}".format(len(token_type_ids), MAX_LEN)

        choices_features.append({
            "input_ids": input_ids,
            "attention_mask": attention_mask,
            "token_type_ids": token_type_ids,
            })

    labels = label_map.get(x["answer"], -1)
    label = torch.tensor(labels).long()

    return {
            "id": x["id"],
            "label": label,
            "input_ids": torch.tensor([cf["input_ids"] for cf in choices_features]),
            "attention_mask": torch.tensor([cf["attention_mask"] for cf in choices_features]),
            "token_type_ids": torch.tensor([cf["token_type_ids"] for cf in choices_features]),
            }


def get_dataloader(tokenizer, datadir: str, cachedir: str = "./"):
    datadir = Path(datadir)
    cachedir = Path(cachedir)
    
    preprocessor = partial(preprocess, tokenizer)

    test_samples = []
    with open(datadir / "test_complete.jsonl") as f:
        for item in json_lines.reader(f):
            test_samples.append(item)
    test = raw_samples_to_dataset(test_samples,t_dataset)
    test_dataloader = DataLoader(
            test.map(preprocessor).save(cachedir / "test_openbook.cache"),
            sampler=SequentialSampler(test),
            batch_size=BATCH_SIZE
            )

    return test_dataloader

In [ ]:
import time

class TestModel(pl.LightningModule):

    def __init__(self, model, test_dataloader):
        super(TestModel, self).__init__()

        self.model = model
        self._test_dataloader = test_dataloader

    def test_step(self, batch, batch_idx):
        ids = batch["id"]
        labels = batch["label"]
        input_ids = batch["input_ids"]
        attention_mask = batch["attention_mask"]
        token_type_ids = batch["token_type_ids"]

        outputs = self.model(
                input_ids,
                token_type_ids=token_type_ids,
                attention_mask=attention_mask,
                labels=labels
                )
        
        labels_hat = torch.argmax(outputs.logits, dim=1)
        print(labels_hat)
        print(labels)
        print(batch["label"])
        print(ids)
        print(outputs.logits)
        i = 0
        j = int(BATCH_SIZE/torch.cuda.device_count())
        for element in outputs.logits:
            print(element)
            print(torch.cuda.current_device()*j+i)
            print("---------------")
#            print(ids[torch.cuda.current_device()*j+i])
            for element2 in t_dataset:
                if element2["id"] == ids[torch.cuda.current_device()*j+i]:
#                    print("!!!!!!!!!!!!!") 
                    element2["optionscore"] = element.cpu().numpy()
#                    print(element2["optionscore"])
            i+=1
#        print(labels)
        time.sleep(0.1)
        acc = FM.accuracy(labels_hat, labels)
#        print(acc)
        self.log('test_acc', acc, on_step=True, on_epoch=True, prog_bar=True, logger=True)

    def test_dataloader(self):
      return self._test_dataloader

In [ ]:
for element in t_dataset:
    if element["id"] == "8-343":
        print(element["optionscore"]) 
#        element["optionscore"] = [1,2,3,4]
        print(element["optionscore"])

[-0.29421133  0.09147942  3.5250065  -0.6242566 ]
[-0.29421133  0.09147942  3.5250065  -0.6242566 ]


In [ ]:
t_dataset = []
tokenizer = AlbertTokenizer.from_pretrained("albert-base-v2", do_lower_case=True)
test_dataloader = get_dataloader(tokenizer, './OpenBookQA-V1-Sep2018/Data/Additional')
pickle.dump(test_dataloader, open("test_dataloader.pkl", "wb"))

05/14/2021 18:23:13 - INFO - elasticsearch -   POST http://localhost:9200/document/_search [status:200 request:10.491s]
05/14/2021 18:23:14 - INFO - elasticsearch -   POST http://localhost:9200/document/_search [status:200 request:1.323s]
05/14/2021 18:23:15 - INFO - elasticsearch -   POST http://localhost:9200/document/_search [status:200 request:1.225s]
05/14/2021 18:23:17 - INFO - elasticsearch -   POST http://localhost:9200/document/_search [status:200 request:1.507s]
05/14/2021 18:23:18 - INFO - elasticsearch -   POST http://localhost:9200/document/_search [status:200 request:1.146s]
05/14/2021 18:23:18 - INFO - elasticsearch -   POST http://localhost:9200/document/_search [status:200 request:0.173s]
05/14/2021 18:23:18 - INFO - elasticsearch -   POST http://localhost:9200/document/_search [status:200 request:0.131s]
05/14/2021 18:23:19 - INFO - elasticsearch -   POST http://localhost:9200/document/_search [status:200 request:0.298s]
05/14/2021 18:23:19 - INFO - elasticsearch -   

250


05/14/2021 18:26:09 - INFO - elasticsearch -   POST http://localhost:9200/document/_search [status:200 request:0.162s]
05/14/2021 18:26:09 - INFO - elasticsearch -   POST http://localhost:9200/document/_search [status:200 request:0.130s]
05/14/2021 18:26:09 - INFO - elasticsearch -   POST http://localhost:9200/document/_search [status:200 request:0.141s]
05/14/2021 18:26:09 - INFO - elasticsearch -   POST http://localhost:9200/document/_search [status:200 request:0.109s]
05/14/2021 18:26:09 - INFO - elasticsearch -   POST http://localhost:9200/document/_search [status:200 request:0.081s]
05/14/2021 18:26:09 - INFO - elasticsearch -   POST http://localhost:9200/document/_search [status:200 request:0.099s]
05/14/2021 18:26:09 - INFO - elasticsearch -   POST http://localhost:9200/document/_search [status:200 request:0.106s]
05/14/2021 18:26:09 - INFO - elasticsearch -   POST http://localhost:9200/document/_search [status:200 request:0.012s]
05/14/2021 18:26:10 - INFO - elasticsearch -   P

500


05/14/2021 18:28:35 - INFO - elasticsearch -   POST http://localhost:9200/document/_search [status:200 request:0.173s]
05/14/2021 18:28:35 - INFO - elasticsearch -   POST http://localhost:9200/document/_search [status:200 request:0.146s]
05/14/2021 18:28:35 - INFO - elasticsearch -   POST http://localhost:9200/document/_search [status:200 request:0.150s]


Loading data from test_openbook.cache...


In [ ]:
print(len(t_dataset))
print(t_dataset[0])

500
{'id': '8-343', 'facts': ['Poor people save money so they can afford to buy chicken for breaking their fast after the long fasting period (fazika zom) during Lent.\n', 'Companies typically budget money over many years, so that they can afford remodeling efforts when necessary, regardless of economic conditions.\n', 'Nice way to make money facebook.\n', 'Will people feel that they need to end their lives earlier to save money?\n', 'Poor people save money so they can afford to buy chicken for breaking their fast after the long fasting period (fazika zom) during Lent.\n', 'Companies typically budget money over many years, so that they can afford remodeling efforts when necessary, regardless of economic conditions.\n', 'Will people feel that they need to end their lives earlier to save money?\n', 'This project is easy enough for the novice gardener and attractive to anyone who wants to save money on their garden budget.\n', 'Poor people save money so they can afford to buy chicken for 

In [ ]:
checkpoint_path = "./albert-openbook-epoch=10-val_loss_epoch=0.87.ckpt"
checkpoint = torch.load(checkpoint_path)

In [ ]:
# important !!! 
# please read it !!!
# in general you can use the code below to reload the model, but some keys in checkpoint[state_dict'] is a little
# different from the trainer.model.model.state_dict(). So we have to adjust it manually.

# from transformers import AlbertConfig
# config = AlbertConfig.from_pretrained('albert-base-v2')
# m = AlbertForMultipleChoice.from_pretrained(pretrained_model_name_or_path= None, config=config, state_dict=trainer.model.model.state_dict())

new_checkpoint = {}

for key in checkpoint['state_dict'].keys():
  if 'model' in key:
    new_key = key[6:]
    new_checkpoint[new_key] = checkpoint['state_dict'][key]
  else:
    new_checkpoint[key] = checkpoint['state_dict'][key]

In [ ]:
from transformers import AlbertConfig
config = AlbertConfig.from_pretrained('albert-base-v2')
m = AlbertForMultipleChoice.from_pretrained(pretrained_model_name_or_path= None, config=config, state_dict=new_checkpoint)

In [ ]:
trainer_for_test = pl.Trainer(gpus=-1, accelerator='dp')
model_for_test = TestModel(m, test_dataloader)

05/14/2021 20:09:01 - INFO - pytorch_lightning.utilities.distributed -   GPU available: True, used: True
05/14/2021 20:09:01 - INFO - pytorch_lightning.utilities.distributed -   TPU available: False, using: 0 TPU cores


In [ ]:
trainer_for_test.test(model=model_for_test)

05/14/2021 20:09:02 - INFO - pytorch_lightning.accelerators.gpu -   LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0,1,2,3]


Testing: 0it [00:00, ?it/s]

tensor([2, 2], device='cuda:2')
tensor([3, 1], device='cuda:3')tensor([2, 2], device='cuda:1')

tensor([2, 0], device='cuda:0')tensor([2, 2], device='cuda:2')

tensor([2, 2], device='cuda:1')
tensor([1, 0], device='cuda:0')tensor([2, 1], device='cuda:3')tensor([2, 2], device='cuda:2')


['8-343', '1129', '880', '7-999', '8-464', '9-794', '9-1163', '9-322']
tensor([2, 1], device='cuda:3')tensor([2, 2], device='cuda:1')

['8-343', '1129', '880', '7-999', '8-464', '9-794', '9-1163', '9-322']
tensor([1, 0], device='cuda:0')['8-343', '1129', '880', '7-999', '8-464', '9-794', '9-1163', '9-322']

['8-343', '1129', '880', '7-999', '8-464', '9-794', '9-1163', '9-322']
tensor([[-1.1794,  1.5428,  5.1917, -1.1807],
        [ 1.6588,  0.2451,  5.7222, -0.8975]], device='cuda:2')
tensor([[-0.2942,  0.0915,  3.5250, -0.6243],
        [ 0.4175,  0.1026, -1.5825, -1.3378]], device='cuda:0')tensor([[-0.1201, -1.8056,  0.5813, -2.1154],
        [ 6.6615,  6.0921,  7.6265,  7.1833]], device='cuda:1')
ten

IndexError: Caught IndexError in replica 2 on device 2.
Original Traceback (most recent call last):
  File "/pfs/data5/home/st/st_us-051200/st_st171103/testenv/lib64/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/pfs/data5/home/st/st_us-051200/st_st171103/testenv/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/pfs/data5/home/st/st_us-051200/st_st171103/testenv/lib64/python3.6/site-packages/pytorch_lightning/overrides/data_parallel.py", line 77, in forward
    output = super().forward(*inputs, **kwargs)
  File "/pfs/data5/home/st/st_us-051200/st_st171103/testenv/lib64/python3.6/site-packages/pytorch_lightning/overrides/base.py", line 55, in forward
    output = self.module.test_step(*inputs, **kwargs)
  File "<ipython-input-101-d040a6ec9db0>", line 39, in test_step
    if element2["id"] == ids[torch.cuda.current_device()*j+i]:
IndexError: list index out of range
